spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/project_db
    username: postgres
    password: 123

  jpa:
    database: postgresql
    hibernate:
      ddl-auto: validate

    properties:
      hibernate:
        format_sql: true
        show_sql: true